source 'https://rubygems.org'

gem 'rails', '3.2.7'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'
gem 'execjs'
gem 'therubyracer'

gem "omniauth-facebook"
gem "devise", ">= 2.1.2"

gem "mongoid", "~> 3.0.0"

# 테스팅과 관련한 rspec, 그리고 mongoid를위한 rspec
gem 'rspec-rails', :group => [:test]
#gem 'spork', :group=>[:test]
gem 'capybara', :group => [:test]
gem 'database_cleaner', :group => :test
#gem 'factory_girl_rails', :group => :test
gem 'mongoid-rspec', :group => :test


# pagination을 위한 gem
gem 'kaminari'


# 이미지 프로세싱.
gem "rmagick"


# 파일 업로드용 paperclip gem.
#gem "paperclip", :git => "git://github.com/thoughtbot/paperclip.git"
gem "mongoid-paperclip", :require => "mongoid_paperclip"



# Delayed job 관련 gem
# After running bundle install, create the indexes (and don't forget to do this on your production database):
# > script/rails runner 'Delayed::Backend::Mongoid::Job.create_indexes'
# > script/delayed_job start  
gem 'delayed_job_mongoid'
gem "daemons"


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
#
#
#
#

